// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpuxtysbchpscncbcmnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwdXh0eXNiY2hwc2NuY2JjbW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDE2MTQsImV4cCI6MjA2NDExNzYxNH0.q_qDIp4e85lswlzNgh3q1gjs0fSBRt4yIkpJc9hDft0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);